package formularios;

import dao.RubroDao;
import dao.SubRubroDao;
import datos.Rubro;
import datos.SubRubro;
import java.text.DecimalFormat;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane; 
import javax.swing.SwingUtilities;

public class frameRubros extends javax.swing.JInternalFrame {
    private boolean hayRubros=false;
    private int rubroSeleccionado;

    public frameRubros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaRubros = new javax.swing.JList();
        cmdAgregarRubro = new javax.swing.JButton();
        cdmBorrarRubro = new javax.swing.JButton();
        cmdActualizarRubro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        cmdAgregar1 = new javax.swing.JButton();
        cdmBorrar1 = new javax.swing.JButton();
        cmdActualizar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaSubRubros = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        cmdActualizarSubRubro = new javax.swing.JButton();
        cmdBorrarSubRubro = new javax.swing.JButton();
        cmdAgregarSubRubro = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setClosable(true);
        setTitle("Rubros y subrubros");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaRubros.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cargando lista..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaRubros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRubros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRubrosMouseClicked(evt);
            }
        });
        listaRubros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaRubrosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaRubros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 40, 175, 216));

        cmdAgregarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas-mini-mini.png"))); // NOI18N
        cmdAgregarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarRubroActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAgregarRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 262, 32, 32));

        cdmBorrarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menos-mini-mini.png"))); // NOI18N
        getContentPane().add(cdmBorrarRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 262, 32, 32));

        cmdActualizarRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh-mini.png"))); // NOI18N
        getContentPane().add(cmdActualizarRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 262, 32, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Rubros:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, -1, -1));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Rubros y subrubros");
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        cmdAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas-mini-mini.png"))); // NOI18N

        cdmBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menos-mini-mini.png"))); // NOI18N

        cmdActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh-mini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Rubros:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(cmdAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cdmBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdmBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmdAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 153, 0, 0));

        jScrollPane3.setViewportView(listaSubRubros);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 175, 216));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Sub-Rubros:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 14, -1, -1));

        cmdActualizarSubRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh-mini.png"))); // NOI18N
        cmdActualizarSubRubro.setEnabled(false);
        getContentPane().add(cmdActualizarSubRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 262, 32, 32));

        cmdBorrarSubRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menos-mini-mini.png"))); // NOI18N
        cmdBorrarSubRubro.setEnabled(false);
        getContentPane().add(cmdBorrarSubRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 262, 32, 32));

        cmdAgregarSubRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas-mini-mini.png"))); // NOI18N
        cmdAgregarSubRubro.setEnabled(false);
        cmdAgregarSubRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarSubRubroActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAgregarSubRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 262, 32, 32));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 324, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        framePrincipal.sing.ventanaRubros(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jInternalFrame1formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formInternalFrameClosing

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.setSize(416,378);
        llenarListaRubros();
    }//GEN-LAST:event_formInternalFrameActivated

    private void cmdAgregarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarRubroActionPerformed
        String nombreRubroNuevo ="";
        
        do{
        nombreRubroNuevo = JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo rubro");
        } while("".equals(nombreRubroNuevo));
        
        if(nombreRubroNuevo!=null){
            RubroDao rubroDao = new RubroDao();
            Rubro r1 = new Rubro(nombreRubroNuevo);
            rubroDao.guardaRubro(r1);
        }
        llenarListaRubros();
    }//GEN-LAST:event_cmdAgregarRubroActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void listaRubrosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaRubrosValueChanged
        
    }//GEN-LAST:event_listaRubrosValueChanged

    private void listaRubrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRubrosMouseClicked
       llenarListaSubRubros();
    }//GEN-LAST:event_listaRubrosMouseClicked

    private void cmdAgregarSubRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarSubRubroActionPerformed
        dialogAddSubRubro agregarRubro = new dialogAddSubRubro(new JFrame(),true);
        agregarRubro.setLocationRelativeTo(this);
        agregarRubro.setTitle("Agregando en rubro "+(new RubroDao().traerRubro(this.rubroSeleccionado).getNombre()));
        agregarRubro.setVisible(true);
        
    }//GEN-LAST:event_cmdAgregarSubRubroActionPerformed

    public void agregarSubRubro(String nombre, String precioC, String precioV){
        Rubro r1 = new RubroDao().traerRubro(this.rubroSeleccionado);
        SubRubro s1 = new SubRubro(r1,nombre,Double.parseDouble(precioC),Double.parseDouble(precioV),new GregorianCalendar(),0.0);
        new SubRubroDao().guardarSubRubro(s1);
        llenarListaSubRubros();
    }
    
    private void llenarListaSubRubros(){
        if(this.hayRubros){
            BotonesSubRubro(true);
            String palabra = (String) listaRubros.getSelectedValue();
            int id=Integer.parseInt(palabra.substring(0, 1));
            this.rubroSeleccionado=id;
            SubRubroDao subRubroDao = new SubRubroDao();
            List<SubRubro> lista = subRubroDao.traerDeUnRubro(id);
            
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<lista.size(); i++){
                model.addElement(lista.get(i).getNombre());
            }
            listaSubRubros.setModel(model);
        }
    }
    
    private void llenarListaRubros(){
        SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                RubroDao rubroDao = new RubroDao();
                List<Rubro> lista = rubroDao.traerListaRubros();
                int cant = lista.size();
                DefaultListModel model = new DefaultListModel();
                if (0!=cant){
                    DecimalFormat df = new DecimalFormat("0");
                    int val = (int) 100/cant;
                    jProgressBar1.setValue(0);

                    
                    for(int i=0; i<lista.size(); i++){
                        model.addElement(lista.get(i).getIdRubro()+" - "+lista.get(i).getNombre());
                        jProgressBar1.setValue(jProgressBar1.getValue()+val);
                    }
                    
                    jProgressBar1.setValue(100);
                    hayRubros=true;
                } else{
                    hayRubros=false;
                }
                listaRubros.setModel(model);
                BotonesSubRubro(false);
            }
        });
    }
    
    private void BotonesSubRubro(boolean b){
        cmdActualizarSubRubro.setEnabled(b);
        cmdAgregarSubRubro.setEnabled(b);
        cmdBorrarSubRubro.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdmBorrar1;
    private javax.swing.JButton cdmBorrarRubro;
    private javax.swing.JButton cmdActualizar1;
    private javax.swing.JButton cmdActualizarRubro;
    private javax.swing.JButton cmdActualizarSubRubro;
    private javax.swing.JButton cmdAgregar1;
    private javax.swing.JButton cmdAgregarRubro;
    private javax.swing.JButton cmdAgregarSubRubro;
    private javax.swing.JButton cmdBorrarSubRubro;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaRubros;
    private javax.swing.JList listaSubRubros;
    // End of variables declaration//GEN-END:variables
}
