/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import clasesPrincipales.Singleton;
import dao.RubroDao;
import datos.Rubro;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author joshua
 */
public class framePrincipal extends javax.swing.JFrame {
    static public Singleton sing = Singleton.getInstance();
    
    /**
     * Creates new form framePrincipal
     */
    public framePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subEscritorio = new javax.swing.JDesktopPane();
        cmdListar = new javax.swing.JButton();
        cmdVenta = new javax.swing.JButton();
        cmdProveedores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuArticulos = new javax.swing.JMenu();
        mnuArticulosListar = new javax.swing.JMenuItem();
        mnuArticulosAgregar = new javax.swing.JMenuItem();
        mnuRubros = new javax.swing.JMenu();
        mnuRubrosRubros = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        mnuProveedoresVer = new javax.swing.JMenuItem();
        mnuProveedoresAdd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Papelera M&M");

        subEscritorio.setDesktopManager(null);

        javax.swing.GroupLayout subEscritorioLayout = new javax.swing.GroupLayout(subEscritorio);
        subEscritorio.setLayout(subEscritorioLayout);
        subEscritorioLayout.setHorizontalGroup(
            subEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subEscritorioLayout.setVerticalGroup(
            subEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        cmdListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa-mini.png"))); // NOI18N
        cmdListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListarActionPerformed(evt);
            }
        });

        cmdVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito-mini.png"))); // NOI18N
        cmdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentaActionPerformed(evt);
            }
        });

        cmdProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prov-mini.png"))); // NOI18N
        cmdProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProveedoresActionPerformed(evt);
            }
        });

        jButton1.setText("Probar Conexión a la DB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mnuArchivo.setText("Archivo");

        mnuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoSalir);

        jMenuBar1.add(mnuArchivo);

        mnuArticulos.setText("Articulos");

        mnuArticulosListar.setText("Listar");
        mnuArticulosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArticulosListarActionPerformed(evt);
            }
        });
        mnuArticulos.add(mnuArticulosListar);

        mnuArticulosAgregar.setText("Agregar");
        mnuArticulosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArticulosAgregarActionPerformed(evt);
            }
        });
        mnuArticulos.add(mnuArticulosAgregar);

        jMenuBar1.add(mnuArticulos);

        mnuRubros.setText("Rubros");

        mnuRubrosRubros.setText("Editar");
        mnuRubrosRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRubrosRubrosActionPerformed(evt);
            }
        });
        mnuRubros.add(mnuRubrosRubros);

        jMenuBar1.add(mnuRubros);

        mnuProveedores.setText("Proveedores");

        mnuProveedoresVer.setText("Ver lista");
        mnuProveedores.add(mnuProveedoresVer);

        mnuProveedoresAdd.setText("Agregar");
        mnuProveedores.add(mnuProveedoresAdd);

        jMenuBar1.add(mnuProveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subEscritorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdListar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)
                        .addGap(0, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdListar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    private void mnuArticulosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArticulosListarActionPerformed
        sing.ventanaListarArticulos(true);
    }//GEN-LAST:event_mnuArticulosListarActionPerformed

    private void cmdListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarActionPerformed
        sing.ventanaListarArticulos(true);
    }//GEN-LAST:event_cmdListarActionPerformed

    private void cmdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdVentaActionPerformed

    private void mnuRubrosRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRubrosRubrosActionPerformed
        sing.ventanaRubros(true);
    }//GEN-LAST:event_mnuRubrosRubrosActionPerformed

    private void mnuArticulosAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArticulosAgregarActionPerformed
        sing.ventanaAgregarArticulo(true);
    }//GEN-LAST:event_mnuArticulosAgregarActionPerformed

    private void cmdProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProveedoresActionPerformed
        sing.ventanaProveedores(true);
    }//GEN-LAST:event_cmdProveedoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Rubro> lstRubro = new RubroDao().traerListaRubros();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                    JFrame.setDefaultLookAndFeelDecorated(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                }
                framePrincipal princ = new framePrincipal();
                //princ.setExtendedState(framePrincipal.MAXIMIZED_BOTH);
                princ.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cmdListar;
    public static javax.swing.JButton cmdProveedores;
    public static javax.swing.JButton cmdVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoSalir;
    public static javax.swing.JMenu mnuArticulos;
    public static javax.swing.JMenuItem mnuArticulosAgregar;
    public static javax.swing.JMenuItem mnuArticulosListar;
    public static javax.swing.JMenu mnuProveedores;
    public static javax.swing.JMenuItem mnuProveedoresAdd;
    public static javax.swing.JMenuItem mnuProveedoresVer;
    public static javax.swing.JMenu mnuRubros;
    public static javax.swing.JMenuItem mnuRubrosRubros;
    public static javax.swing.JDesktopPane subEscritorio;
    // End of variables declaration//GEN-END:variables
}
